# Generated by Django 2.2.7 on 2019-12-04 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra', models.CharField(max_length=200)),
                ('num_pedido', models.CharField(max_length=200)),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('delegacion', models.CharField(max_length=200)),
                ('producto_id', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('estado_pedido', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediciones_pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
