# Generated by Django 2.2.7 on 2019-12-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delegacion',
            field=models.CharField(choices=[('', ''), ('Granada', 'Granada'), ('Galicia', 'Galicia'), ('Zaragoza', 'Zaragoza')], max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='estado_pedido',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('Preparado', 'Preparado'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Devuelto', 'Devuelto'), ('Cancelado', 'Cancelado')], default='Recibido', max_length=50),
        ),
    ]
